spring:
  datasource:
    url: jdbc:mysql://[db_name].cvhzq4aq6qx6.sa-east-1.rds.amazonaws.com:3306/ebdb
    username: [username]
    password: [password]
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: false